# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/app_state.dart
    - lib/auth/**
    - lib/pages/**
    - lib/flutter_flow/**
    - lib/backend/schema/**
    - lib/custom_code/**
    - lib/main.dart
    - lib/backend/api_requests/**
    - lib/backend/backend.dart
    - lib/backend/custom_cloud_functions/**
    - lib/backend/firebase/**
    - lib/backend/api_manager.dart
    - lib/backend/api_calls.dart
    - test_app.dart
    - flutter/**

linter:
  rules:
    unnecessary_string_escapes: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options